global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'monitoring'
scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.2.84:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.2.10:8080','192.168.2.201:8080','192.168.2.84:8080','192.168.2.170:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.2.10:9100','192.168.2.201:9100','192.168.2.84:9100','192.168.2.170:9100']